POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Johnny",
    "number": "112"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "number": "112"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Johnny"
}